### ISSUE TITLE
Possible bug with checkpointing

### ISSUE THREAD

**Issue by aliostad** [openzipkin/zipkin-azure#10]
Everytime I run the collector, I checkpoint some partitions without adding new spans - possibly pointing to the fact checkpointing is not working.

[created by mistake here https://github.com/openzipkin/zipkin-csharp/issues/30]

**Comment by aliostad** [comment]
So it turns out Azure EventHub, unlike Kafka, leaves keeping track of checkpoints entirely to consumers. So our client used its hostname (by default a UUID) as the blob path hence every time checkpointing would start from the beginning. So this fix uses a constant path - that can obviously be overridden.

I love to be able to do an integration test but without real eventhub looks impossible.

Happy for me to add this fix with no apparent test?

**Comment by adriancole** [comment]
hey there. yeah so I think what we'd do is put in a unit test that verifies a constant path is the default for the blob path, and in the comment of that unit test, say what you said above.

What this does is it keeps track of the rationale, and when we can get a "live test" ex one driven by a real account, we could backfill by reading that comment.

**Comment by adriancole** [comment]
@aliostad in other words, go for it sounds like a property change, a test with explanation and probably some doc/readme updates at least to say what the default is

**Comment by aliostad** [comment]
@adriancole thanks. Will do, add a unit test. Also some doc update.
