### ISSUE TITLE
LazyRegisterEventProcessor is not actually an event processor

### ISSUE THREAD

**Issue by aliostad** [openzipkin/zipkin-azure#12]
`LazyRegisterEventProcessor` is actually an LazyRegisterEventProcessor**Host**. There is a big difference between the *host* and *processor*. I suggest renaming. to `LazyRegisterEventProcessorHost`.

**Comment by adriancole** [comment]
"lazy register eventprocessor" is indeed an abbreviation for "lazy register eventprocessor with host". Is there something else that you'd expect the eventprocessor to be lazily registered with, where appending host resolves that ambiguity?

**Comment by adriancole** [comment]
either way I don't care on this one. will rename to append host

**Comment by adriancole** [comment]
here you go. https://github.com/openzipkin/zipkin-azure/pull/15

**Comment by aliostad** [comment]
Thank you
