### ISSUE TITLE
Reduce configuration to one (or max two) short properties

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-azure#5]
Right now, there's a long description of creating a properties file which includes all but one property. Each of these are in long form, like `zipkin.collector.eventhub.connection-string`. To get a similar experience with other services, we'd ideally have one or two required properties in short form (like `EVENTHUB_CONNECTION_STRING`, taking anything we can from host installed defaults (if exist)

The following are good examples of where a short env variable is available, which allows people to literally hand type a commandline in as needed!
* [elasticsearch-http-aws](https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#elasticsearch-storage) is integrated with built-in credentials. Ex you only need to supply `ES_AWS_DOMAIN` to use hosted storage.
* [stackdriver-zipkin](https://github.com/GoogleCloudPlatform/stackdriver-zipkin#configuration) similarly only needs `PROJECT_ID`

**Comment by aliostad** [comment]
Currently only 2 conf params are mandatory:

- EVENTHUB_CONNECTION_STRING
- Azure Storage Connection String

The first one being passed using the property launcher which leaves only the second one - I have not tried but I guess we can pass system variables via command line.

I will check.

**Comment by adriancole** [comment]
here's an implementation along with some fixes and other suggestions https://github.com/openzipkin/zipkin-azure/pull/9

**Comment by adriancole** [comment]
actually, it doesn't completely solve this because I still don't have good docs or instructions to derive the mandatory properties.. @aliostad maybe you can help with that after the fact?

**Comment by aliostad** [comment]
Is it not better to read environment variables in the auto configuration so not having to rely on the YAML file? e.g. `System.getenv("EVENTHUB_CONNECTION_STRING")`, etc

**Comment by adriancole** [comment]
>
> Is it not better to read environment variables in the auto configuration
> so not having to rely on the YAML file? e.g. System.getenv("EVENTHUB_
> CONNECTION_STRING"), etc
>
This is only to support the server profile, which can be disabled. The
auto-configuration files itself shouldn't read the environment, as things
like profiles address that concern.
